package org.newtonia;

// Java half of the Google Play Games Services achievements backend
// (ACHIEVEMENTS.md §2). The native half — play_games_achievements.cpp,
// compiled under PLAY_GAMES_BUILD — owns the symbolic→resource-name mapping
// table and calls the two static entry points below over JNI from the game
// thread; everything here immediately hops to the UI thread, where all
// state lives (no locking needed).
//
// The Play Games v2 SDK signs the player in automatically once
// PlayGamesSdk.initialize() has run; there is no sign-in UI in the game.
// Earns that arrive before the async sign-in check resolves (or while the
// player is signed out) are held in an in-memory queue merged per
// achievement at maximum percent, and flushed when a later check succeeds —
// re-checked on every activity resume (NewtoniaActivity.onResume). Signed-in
// earns go straight to AchievementsClient, whose fire-and-forget
// unlock()/setSteps() calls are cached by Play services on the device and
// synced when connectivity returns, so offline-while-signed-in delivery is
// the platform's job (ACHIEVEMENTS.md §2 "Offline earns"). Signed-out play
// earning nothing if the process dies first is allowed (XR-055): the
// counter-backed achievements re-derive from persisted stats next session
// anyway.
//
// Achievement IDs are generated by the Play Console and pasted into
// res/values/games-ids.xml under the resource names fixed by the native
// mapping table. A resource that doesn't resolve means the console entry
// hasn't been created yet — the earn is dropped with a one-shot log, never
// a crash, and the same-named entry landing later is the whole fix.

import android.app.Activity;
import android.util.Log;

import com.google.android.gms.games.AchievementsClient;
import com.google.android.gms.games.AuthenticationResult;
import com.google.android.gms.games.GamesSignInClient;
import com.google.android.gms.games.PlayGames;
import com.google.android.gms.games.PlayGamesSdk;
import com.google.android.gms.tasks.OnCompleteListener;
import com.google.android.gms.tasks.Task;

import java.util.HashMap;
import java.util.HashSet;
import java.util.Map;
import java.util.Set;

public final class PlayGamesAchievements {

    private static final String TAG = "NewtoniaPlayGames";

    // All fields are touched only on the UI thread.
    private static Activity sActivity;
    private static boolean sSdkReady;
    private static boolean sAuthenticated;
    private static boolean sAuthCheckInFlight;
    // Earns awaiting sign-in, merged per resource name at max percent.
    private static final Map<String, Earn> sPending = new HashMap<>();
    // One-shot log dedupe for resource names missing from games-ids.xml.
    private static final Set<String> sWarnedUnmapped = new HashSet<>();

    private static final class Earn {
        int pct;
        final boolean incremental;
        Earn(int pct, boolean incremental) {
            this.pct = pct;
            this.incremental = incremental;
        }
    }

    private PlayGamesAchievements() {}

    // Native entry point (game thread): called from Achievements::init().
    // Re-entrant for SDL's kept-alive-process restarts — just refreshes the
    // activity reference and re-checks sign-in.
    public static void init(final Activity activity) {
        activity.runOnUiThread(new Runnable() {
            @Override public void run() {
                sActivity = activity;
                if (!sSdkReady) {
                    try {
                        PlayGamesSdk.initialize(activity);
                        sSdkReady = true;
                    } catch (Throwable t) {
                        // Missing APP_ID meta-data or absent Play services
                        // must never take the game down — achievements just
                        // stay off for the session.
                        Log.w(TAG, "Play Games SDK unavailable — achievements disabled", t);
                        return;
                    }
                }
                checkAuth();
            }
        });
    }

    // NewtoniaActivity.onResume(): the natural retry point — the player may
    // have signed in (or regained connectivity) while the game was
    // backgrounded. A redundant check is cheap and flushing is a no-op when
    // nothing is pending.
    public static void onResume() {
        final Activity activity = sActivity;
        if (activity == null) return;
        activity.runOnUiThread(new Runnable() {
            @Override public void run() {
                if (sSdkReady && !sAuthenticated) checkAuth();
            }
        });
    }

    // Native entry point (game thread): report an earn. pct is 1-100 (100 ==
    // unlock, enforced by the shared seam); incremental mirrors the native
    // mapping table — those achievements are defined in the Play Console as
    // incremental with 100 steps, so pct maps 1:1 to steps.
    public static void report(final String resName, final int pct,
                              final boolean incremental) {
        final Activity activity = sActivity;
        if (activity == null) return;
        activity.runOnUiThread(new Runnable() {
            @Override public void run() {
                if (!sSdkReady) return;
                if (sAuthenticated) {
                    send(resName, pct, incremental);
                    return;
                }
                Earn earn = sPending.get(resName);
                if (earn == null) sPending.put(resName, new Earn(pct, incremental));
                else if (pct > earn.pct) earn.pct = pct;
                checkAuth();  // no-op while a check is already in flight
            }
        });
    }

    private static void checkAuth() {
        if (sAuthCheckInFlight) return;
        sAuthCheckInFlight = true;
        GamesSignInClient client = PlayGames.getGamesSignInClient(sActivity);
        client.isAuthenticated().addOnCompleteListener(sActivity,
                new OnCompleteListener<AuthenticationResult>() {
            @Override public void onComplete(Task<AuthenticationResult> task) {
                // Listener is activity-scoped, so this runs on the UI thread.
                sAuthCheckInFlight = false;
                boolean ok = task.isSuccessful()
                        && task.getResult().isAuthenticated();
                if (ok && !sAuthenticated)
                    Log.i(TAG, "Play Games signed in — achievements live");
                sAuthenticated = ok;
                if (ok) flushPending();
                else Log.i(TAG, "Play Games not signed in — earns held in memory");
            }
        });
    }

    private static void flushPending() {
        for (Map.Entry<String, Earn> e : sPending.entrySet())
            send(e.getKey(), e.getValue().pct, e.getValue().incremental);
        sPending.clear();
    }

    private static void send(String resName, int pct, boolean incremental) {
        int rid = sActivity.getResources().getIdentifier(
                resName, "string", sActivity.getPackageName());
        if (rid == 0) {
            if (sWarnedUnmapped.add(resName))
                Log.w(TAG, "'" + resName + "' missing from games-ids.xml — earn "
                        + "dropped (define the achievement in the Play Console "
                        + "and paste its generated ID under this resource name)");
            return;
        }
        String id = sActivity.getString(rid);
        AchievementsClient client = PlayGames.getAchievementsClient(sActivity);
        if (incremental) {
            // setSteps is "at least this many": lower values are server-side
            // no-ops, so progress is monotonic by construction, and reaching
            // all 100 steps unlocks the achievement — no separate unlock()
            // call, which the Play API disallows for incremental definitions.
            client.setSteps(id, Math.min(pct, 100));
        } else if (pct >= 100) {
            client.unlock(id);
        }
        // pct < 100 on a non-incremental achievement: nothing to report (the
        // native side only sends progress for incremental mappings anyway).
    }
}
