#!/usr/bin/env python3
"""Regenerate net_ca_bundle.cpp — the CA roots the netplay/leaderboard
WebSockets verify against (LEADERBOARD.md S1).

The native sockets run on libdatachannel, whose TLS backends reach NO system
trust store on half our platforms: MbedTLS has none anywhere (the macOS
universal, iOS, Android and Xbox builds), and on Windows OpenSSL does not
consult the CryptoAPI ROOT store while its default verify paths are a Unix
path baked in when OpenSSL was built. Verification there is only possible
against an explicitly supplied CA bundle, so we carry one.

Source: https://curl.se/ca/cacert.pem — curl's build of the Mozilla root
program, the same data every OS ships. Deliberately the FULL bundle rather
than the handful of roots Cloudflare currently issues from (Let's Encrypt,
Google Trust Services, SSL.com, Sectigo for backups): Cloudflare picks a CA
per certificate and rotates, so a narrow set is a silent tripwire years out,
and the anchor-pinning it would buy is worth little when the pin has to
include four of the largest public CAs anyway. The security win here is
VERIFICATION, not pinning.

The output is committed so no build ever needs the network. Rerun after a
Mozilla root-program change (a year or two apart in practice):

    ./generate_ca_bundle.py            # fetch + regenerate
    ./generate_ca_bundle.py FILE.pem   # regenerate from a local copy
"""
import datetime
import hashlib
import os
import sys
import urllib.request

SOURCE_URL = "https://curl.se/ca/cacert.pem"
OUT = os.path.join(os.path.dirname(os.path.abspath(__file__)),
                   "net_ca_bundle.cpp")

# Per-literal cap. MSVC rejects a string literal over 65535 bytes AFTER
# adjacent-literal concatenation, and an escaped newline costs two bytes, so
# 16 KB of PEM can never approach it.
CHUNK = 16 * 1024


def fetch(argv):
    if len(argv) > 1:
        with open(argv[1], "rb") as f:
            return f.read()
    print(f"fetching {SOURCE_URL}")
    with urllib.request.urlopen(SOURCE_URL, timeout=60) as r:
        return r.read()


BEGIN = b"-----BEGIN CERTIFICATE-----"
END = b"-----END CERTIFICATE-----"


def certificate_blocks(pem):
    """Just the PEM blocks, dropping curl's commentary.

    The upstream file prefixes each certificate with its subject name, and
    those carry UTF-8 ("Autoridad de Certificacion Firmaprofesional" and
    friends). A parser wants none of it, and a C string literal wants it even
    less — so embed the base64 blocks alone and let the source hash in the
    header be the provenance.
    """
    out = []
    pos = 0
    while True:
        start = pem.find(BEGIN, pos)
        if start < 0:
            break
        stop = pem.find(END, start)
        if stop < 0:
            raise SystemExit("unterminated certificate block - refusing")
        out.append(pem[start:stop + len(END)])
        pos = stop + len(END)
    return b"\n".join(out) + b"\n"


def c_escape(chunk):
    out = []
    for b in chunk:
        c = chr(b)
        if c == "\\":
            out.append("\\\\")
        elif c == '"':
            out.append('\\"')
        elif c == "\n":
            out.append("\\n")
        elif 0x20 <= b < 0x7F:
            out.append(c)
        else:
            # Certificate blocks are base64 + dashes; anything else means the
            # extraction above let commentary through.
            raise SystemExit(f"non-ASCII byte {b:#x} in bundle - refusing")
    return "".join(out)


def main():
    pem = fetch(sys.argv)
    if b"-----BEGIN CERTIFICATE-----" not in pem:
        raise SystemExit("no certificates in the fetched data - refusing")
    # curl.se serves CRLF-free PEM; normalise anyway so the byte count the
    # game checks against the file on disk is what we actually emit.
    pem = pem.replace(b"\r\n", b"\n")
    certs = pem.count(BEGIN)
    digest = hashlib.sha256(pem).hexdigest()
    stamp = datetime.datetime.now(datetime.timezone.utc).strftime("%Y-%m-%d")
    pem = certificate_blocks(pem)

    parts = [pem[i:i + CHUNK] for i in range(0, len(pem), CHUNK)]
    with open(OUT, "w") as f:
        f.write(f"""// GENERATED by generate_ca_bundle.py - do not edit by hand.
//
// CA roots for the netplay/leaderboard WebSockets (LEADERBOARD.md S1).
// Source: {SOURCE_URL} (Mozilla root program via curl)
//   regenerated : {stamp}
//   certificates: {certs}
//   sha256      : {digest}   (of the fetched file, before comments were
//                             stripped - `curl -s {SOURCE_URL} | sha256sum`)
//
// Compiled only into builds that own a native WebSocket; the web build uses
// the browser's verified socket and netless builds have none.

#ifdef NEWTONIA_NET_RTC

extern const char *const net_ca_bundle_parts[];
extern const unsigned net_ca_bundle_bytes;

// PEM split into per-literal chunks (MSVC caps a literal at 64 KB).
const char *const net_ca_bundle_parts[] = {{
""")
        for part in parts:
            f.write(f'    "{c_escape(part)}",\n')
        f.write(f"""    0,
}};

const unsigned net_ca_bundle_bytes = {len(pem)}u;

#endif /* NEWTONIA_NET_RTC */
""")
    print(f"wrote {OUT}: {certs} certificates, {len(pem)} bytes, "
          f"{len(parts)} chunk(s)")


if __name__ == "__main__":
    main()
