// See net_tls.h. Compiled only into builds with a native WebSocket — the web
// build uses the browser's (already verified) socket and netless builds have
// none, so this is an empty translation unit there, like net_board_rtc.cpp.

#ifdef NEWTONIA_NET_RTC

#include "net_tls.h"

#include <SDL.h>

#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#ifdef _WIN32
#include <process.h>   // _getpid
#define getpid _getpid
#else
#include <unistd.h>    // getpid
#endif

// net_ca_bundle.cpp (generated by generate_ca_bundle.py).
extern const char *const net_ca_bundle_parts[];
extern const unsigned net_ca_bundle_bytes;

namespace {

const char *const CA_ORG = "cc.gfm";
const char *const CA_APP = "newtonia";
const char *const CA_FILE = "cacert.pem";

// Write the embedded roots out, but only when the file on disk is missing or
// a different size — a game update ships new roots, and the size check is
// what notices. (Not a hash: this runs on the connect path and the file is
// ours, not an attacker's — a tampered local bundle means the machine is
// already lost.)
std::string materialize() {
  char *dir = SDL_GetPrefPath(CA_ORG, CA_APP);
  if (!dir) {
    SDL_Log("net: tls - no pref path for the CA bundle");
    return std::string();
  }
  std::string path = std::string(dir) + CA_FILE;
  SDL_free(dir);

  bool current = false;
  if (FILE *fp = fopen(path.c_str(), "rb")) {
    if (fseek(fp, 0, SEEK_END) == 0)
      current = ftell(fp) == (long)net_ca_bundle_bytes;
    fclose(fp);
  }
  if (current) return path;

  // Write a private temp file and RENAME it over the target, so the bundle
  // at `path` is only ever complete or absent — never half-written. Two
  // instances of the game share one pref path (the netplay e2e drivers run
  // a host and a client against the same XDG_DATA_HOME), and both reach
  // this on their first connect after an update: a plain fopen("wb") would
  // let one truncate the file while the other's TLS stack is reading it,
  // failing that handshake for no visible reason. Rename is atomic on
  // POSIX; the pid keeps the two writers off each other's temp file.
  char suffix[32];
  snprintf(suffix, sizeof(suffix), ".%ld.tmp", (long)getpid());
  const std::string tmp = path + suffix;

  FILE *fp = fopen(tmp.c_str(), "wb");
  if (!fp) {
    SDL_Log("net: tls - cannot write the CA bundle to %s", tmp.c_str());
    return std::string();
  }
  bool ok = true;
  for (int i = 0; net_ca_bundle_parts[i] && ok; i++) {
    size_t n = strlen(net_ca_bundle_parts[i]);
    ok = fwrite(net_ca_bundle_parts[i], 1, n, fp) == n;
  }
  if (fclose(fp) != 0) ok = false;
  if (ok) {
    // Windows' rename() refuses an existing destination, so clear it first.
    // That reopens a small window there — briefly no bundle rather than a
    // half-written one, which fails safe (the connect declines) instead of
    // verifying against a truncated root set.
#ifdef _WIN32
    remove(path.c_str());
#endif
    ok = rename(tmp.c_str(), path.c_str()) == 0;
  }
  if (!ok) {
    remove(tmp.c_str());
    SDL_Log("net: tls - failed writing the CA bundle to %s", path.c_str());
    return std::string();
  }
  SDL_Log("net: tls - CA bundle written to %s (%u bytes)", path.c_str(),
          net_ca_bundle_bytes);
  return path;
}

}  // namespace

const std::string &net_ca_bundle_path() {
  static std::string path = materialize();
  return path;
}

bool net_tls_insecure() {
  static int cached = -1;
  if (cached < 0) {
    const char *e = getenv("NEWTONIA_NET_TLS_INSECURE");
    cached = (e && e[0] == '1' && e[1] == '\0') ? 1 : 0;
    if (cached)
      SDL_Log("net: tls - VERIFICATION DISABLED by NEWTONIA_NET_TLS_INSECURE "
              "(credentials on this connection are exposed to any on-path "
              "attacker)");
  }
  return cached != 0;
}

#endif /* NEWTONIA_NET_RTC */
