// See net_tls.h. Compiled only into builds with a native WebSocket — the web
// build uses the browser's (already verified) socket and netless builds have
// none, so this is an empty translation unit there, like net_board_rtc.cpp.

#ifdef NEWTONIA_NET_RTC

#include "net_tls.h"

#include <SDL.h>

#include <stdio.h>
#include <stdlib.h>
#include <string.h>

// net_ca_bundle.cpp (generated by generate_ca_bundle.py).
extern const char *const net_ca_bundle_parts[];
extern const unsigned net_ca_bundle_bytes;

namespace {

const char *const CA_ORG = "cc.gfm";
const char *const CA_APP = "newtonia";
const char *const CA_FILE = "cacert.pem";

// Write the embedded roots out, but only when the file on disk is missing or
// a different size — a game update ships new roots, and the size check is
// what notices. (Not a hash: this runs on the connect path and the file is
// ours, not an attacker's — a tampered local bundle means the machine is
// already lost.)
std::string materialize() {
  char *dir = SDL_GetPrefPath(CA_ORG, CA_APP);
  if (!dir) {
    SDL_Log("net: tls - no pref path for the CA bundle");
    return std::string();
  }
  std::string path = std::string(dir) + CA_FILE;
  SDL_free(dir);

  bool current = false;
  if (FILE *fp = fopen(path.c_str(), "rb")) {
    if (fseek(fp, 0, SEEK_END) == 0)
      current = ftell(fp) == (long)net_ca_bundle_bytes;
    fclose(fp);
  }
  if (current) return path;

  FILE *fp = fopen(path.c_str(), "wb");
  if (!fp) {
    SDL_Log("net: tls - cannot write the CA bundle to %s", path.c_str());
    return std::string();
  }
  bool ok = true;
  for (int i = 0; net_ca_bundle_parts[i] && ok; i++) {
    size_t n = strlen(net_ca_bundle_parts[i]);
    ok = fwrite(net_ca_bundle_parts[i], 1, n, fp) == n;
  }
  if (fclose(fp) != 0) ok = false;
  if (!ok) {
    // A half-written bundle is worse than none: it would verify against a
    // truncated root set and fail confusingly. Remove it and report nothing.
    remove(path.c_str());
    SDL_Log("net: tls - failed writing the CA bundle to %s", path.c_str());
    return std::string();
  }
  SDL_Log("net: tls - CA bundle written to %s (%u bytes)", path.c_str(),
          net_ca_bundle_bytes);
  return path;
}

}  // namespace

const std::string &net_ca_bundle_path() {
  static std::string path = materialize();
  return path;
}

bool net_tls_insecure() {
  static int cached = -1;
  if (cached < 0) {
    const char *e = getenv("NEWTONIA_NET_TLS_INSECURE");
    cached = (e && e[0] == '1' && e[1] == '\0') ? 1 : 0;
    if (cached)
      SDL_Log("net: tls - VERIFICATION DISABLED by NEWTONIA_NET_TLS_INSECURE "
              "(credentials on this connection are exposed to any on-path "
              "attacker)");
  }
  return cached != 0;
}

#endif /* NEWTONIA_NET_RTC */
