#ifndef NET_TLS_H
#define NET_TLS_H

// TLS trust material for the native WebSockets (LEADERBOARD.md S1).
//
// The signalling and leaderboard sockets both carry the platform
// VERIFICATION CREDENTIAL (a Steam Web-API ticket, a Play Games single-use
// server auth code, a Game Center signature bundle), and the board socket
// additionally carries the replay published under the player's account. That
// makes an on-path attacker a real threat: capture the credential, drop the
// victim's frame, spend it against the real worker and place a score under
// their attested identity. So these sockets verify the server certificate.
//
// libdatachannel's TLS backends reach no system trust store on half our
// platforms — MbedTLS has none anywhere (macOS universal, iOS, Android,
// Xbox), and on Windows OpenSSL does not consult the CryptoAPI ROOT store
// while its default verify paths are a Unix path baked in at OpenSSL build
// time. So the game carries its own roots (net_ca_bundle.cpp, regenerated by
// generate_ca_bundle.py) and hands libdatachannel the path. Where a real
// system store DOES exist (Linux, non-universal macOS) OpenSSL has already
// loaded it and our bundle simply adds to it.
//
// Passing the bundle needs `caCertificatePemFile` on the C `rtcWsConfiguration`,
// which upstream exposes only on the C++ API — patches/libdatachannel-ws-ca-cert.patch
// adds it (and lets Windows verify when a CA is supplied). Every build path
// that builds libdatachannel applies that patch; a build that somehow misses
// it fails to COMPILE on the unknown field, which is the failure we want.

#include <string>

// Absolute path to the CA bundle on disk, materialized from the embedded
// copy on first call (SDL pref path, "cacert.pem"). Empty when it could not
// be written — on a system-store platform the socket then still verifies,
// on an MbedTLS one the handshake fails closed, and on Windows the connect
// is REFUSED by net_tls_ws_policy below rather than made unverified.
//
// Main thread only (both call sites are connect(), a main-thread op); the
// result is cached for the process lifetime and stays valid forever.
const std::string &net_ca_bundle_path();

// The verification policy both credential-carrying sockets apply — ONE
// function, two call sites, so neither can drift from the other. Fills the
// two rtcWsConfiguration fields (the C struct is an anonymous typedef and
// cannot be forward-declared here, so the caller copies them across).
//
// Returns false when this build would otherwise connect UNVERIFIED — Windows
// with no bundle on disk, where libdatachannel drops verification whenever
// no CA is supplied — and the caller MUST then refuse to connect: no online
// play beats a socket that looks like success while handing the platform
// credential to any on-path attacker (security review 2026-09-08, F3). The
// other platforms never refuse here because they never need to: MbedTLS
// fails closed at the handshake with no roots to verify against, and
// OpenSSL on Linux / plain macOS verifies against the system store it has
// already loaded. NEWTONIA_NET_TLS_INSECURE=1 is the only way through
// without a bundle, and it announces itself in the log.
struct NetTlsWsPolicy {
  bool disable_verification;
  const char *ca_file;   // NULL when no bundle is on disk
};
bool net_tls_ws_policy(NetTlsWsPolicy &out);

// Log what this process will actually do — once, on the first socket that
// asks. Without it there is NO steady-state evidence either way: the bundle
// is written on the first connect after an update and silently reused
// forever after, so "is it verifying?" had no answer short of deleting the
// file or setting the escape hatch. A manual per-platform pass (TESTING.md)
// is this line plus NEWTONIA_SIGNAL_SELFTEST against the real worker.
void net_tls_log_state();

// NEWTONIA_NET_TLS_INSECURE=1 disables certificate verification on both
// sockets. A field-debugging escape hatch for a TLS-terminating middlebox or
// a broken bundle — never set by any shipped build, and logged loudly every
// time it takes effect. There is deliberately NO automatic fallback to
// unverified on handshake failure: that would be a downgrade any attacker
// could force by breaking the first attempt.
bool net_tls_insecure();

#endif /* NET_TLS_H */
